Add native acl reloading
tale/headplane pull request #12
Opened 2024-05-19 22:02 UTC by gageorsburn

2024-05-19 22:56 UTC, tale requested changes

2024-05-19 22:56 UTC, tale commented on app/utils/linux.ts
> +import * as path from 'path';
Looks mostly good, I'll go through the PR soon to switch to the `fs/promises` API, don't worry about that.

2024-05-19 22:56 UTC, tale commented on package.json
> +		"node": ">=19.0.0"
What needs Node.js 19?

2024-05-19 23:17 UTC, gageorsburn commented on package.json
> +		"node": ">=19.0.0"
The crypto dependency

2024-05-26 00:28 UTC, tale approved these changes

2024-05-26 23:43 UTC, tale commented
See f0e4868 😄

2024-05-26 23:43 UTC, closed without merging